name: Daily Build

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Build Electron app
        run: npm run package-linux

      - name: Upload DEB and RPM packages
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: |
            dist/*.deb
            dist/*.rpm
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Build Electron app for Windows
        run: npm run package-win

      - name: Upload EXE package
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts-windows
          path: dist/*.exe
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
